baseURL = "https://stephenc.github.io/"
languageCode = "en-gb"
title = "Stephen's technical blog"
theme = "github-style"

[pagination]
  pagerSize = 10

[params]
  author = "stephenc"
  description = "Longer form musings"
  github = "stephenc"
  linkedin = "stephenalanconnolly"
  avatar = "/images/avatar.jpg"
  keywords = "blog"
  rss = true
  lastmod = true
  userStatusEmoji = "ðŸ˜€"
  headerIcon = "/images/gitHub-mark-white.png"
  menu_title = "stephenc"
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

# Main menu entries
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "legacy"
  name = "Legacy projects"
  url = "/legacy/"
  weight = 2
